name: Crystal CI

on:
  push:
    branches: [core]
  pull_request:
    branches: [core]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards update --ignore-crystal-version
      - name: Check formatting
        run: crystal tool format --check
      - name: Static analysis
        run: ./bin/ameba
      - name: Run tests
        run: ENVIRONMENT=TEST crystal spec --verbose
